// Single icon entry point. Phosphor gives one geometric family with regular / bold / fill
// weights, so active and selected states can switch weight instead of colour alone.
import {
  ArrowClockwise,
  ArrowDownRight,
  ArrowsLeftRight,
  ArrowsOutSimple,
  ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  Atom,
  Bank,
  Bell,
  Briefcase,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  ChartLineUp,
  ChartPieSlice,
  ChatCircleText,
  Check,
  CheckCircle,
  ClockCounterClockwise,
  Copy,
  Cpu,
  Cube,
  DotsThree,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  Factory,
  File,
  FileMagnifyingGlass,
  FileText,
  FirstAidKit,
  GearSix,
  Globe,
  House,
  ImageSquare,
  Info,
  Lightning,
  LinkSimple,
  List,
  LockSimple,
  MagnifyingGlass,
  Microphone,
  Newspaper,
  NotePencil,
  Paperclip,
  Plus,
  ShieldCheck,
  ShoppingCart,
  SidebarSimple,
  SignOut,
  Sparkle,
  SquaresFour,
  Star,
  Stop,
  ThumbsDown,
  ThumbsUp,
  Trash,
  TrendUp,
  User,
  Users,
  WarningCircle,
  Waveform,
  X,
  XCircle,
} from '@phosphor-icons/react'

const MAP = {
  pencil: NotePencil,
  home: House,
  grid: SquaresFour,
  bars: ChartBar,
  users: Users,
  settings: GearSix,
  bell: Bell,
  file: File,
  fileText: FileText,
  fileSearch: FileMagnifyingGlass,
  panel: SidebarSimple,
  chevronDown: CaretDown,
  chevronLeft: CaretLeft,
  chevronRight: CaretRight,
  x: X,
  search: MagnifyingGlass,
  star: Star,
  plus: Plus,
  plusCircle: ImageSquare,
  atom: Atom,
  globe: Globe,
  mic: Microphone,
  wave: Waveform,
  send: ArrowUp,
  stop: Stop,
  expand: ArrowsOutSimple,
  copy: Copy,
  thumbUp: ThumbsUp,
  thumbDown: ThumbsDown,
  cpu: Cpu,
  landmark: Bank,
  hospital: FirstAidKit,
  compare: ArrowsLeftRight,
  cube: Cube,
  more: DotsThree,
  check: Check,
  paperclip: Paperclip,
  link: LinkSimple,
  briefcase: Briefcase,
  clock: ClockCounterClockwise,
  trash: Trash,
  refresh: ArrowClockwise,
  external: ArrowSquareOut,
  cart: ShoppingCart,
  factory: Factory,
  sparkles: Sparkle,
  alert: WarningCircle,
  download: DownloadSimple,
  pie: ChartPieSlice,
  menu: List,
  logout: SignOut,
  user: User,
  lock: LockSimple,
  bolt: Lightning,
  info: Info,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  trendUp: TrendUp,
  eye: Eye,
  eyeOff: EyeSlash,
  chart: ChartLineUp,
  news: Newspaper,
  shield: ShieldCheck,
  chat: ChatCircleText,
  mail: EnvelopeSimple,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
}

const FILLED = new Set(['bolt', 'stop'])

/**
 * <Icon name size weight />. `stroke` is accepted for backwards compatibility:
 * values ≥ 2 map to the bold weight.
 */
export default function Icon({ name, size = 18, weight, stroke, className, style, mirrored }) {
  const Glyph = MAP[name]
  if (!Glyph) return null
  const w = weight || (FILLED.has(name) ? 'fill' : stroke >= 2 || size <= 13 ? 'bold' : 'regular')
  return <Glyph size={size} weight={w} className={className} style={style} mirrored={mirrored} aria-hidden="true" focusable="false" />
}

/** Direction glyph for price moves: a small arrow, no badge. */
export function Trend({ up, size = 12 }) {
  const Glyph = up ? ArrowUpRight : ArrowDownRight
  return <Glyph size={size} weight="bold" className={`trend ${up ? 'is-up' : 'is-down'}`} aria-hidden="true" />
}
